### ISSUE TITLE
Performance issue: lots of memory allocations triggering full GC makes everything slow

### ISSUE THREAD

**Issue by GuiTeK** [jsonapi-serializer/jsonapi-serializer#106] opened 2020-08-05 15:52 UTC
## Context

I'm opening this issue following [this message](https://github.com/jsonapi-serializer/jsonapi-serializer/pull/103#issuecomment-665797603) from @stas.

I'm using jsonapi-serializer in a Rails API project.

## Behavior

When requesting many times an endpoint which uses jsonapi-serializer, a single request will regularly take much more time to complete than the others. For example, normal requests will complete within 100 ms, but let's say 1 out of 100 requests will take _5 seconds_ (instead of 100 ms) to complete.

The root cause of this issue seems to be that jsonapi-serializer makes a lot of memory allocations, and when too much memory has been allocated, **a full GC is triggered**, which is very slow to perform.

The frequency at which this problem arises seems to be **correlated to the size of the payload to serialize**:
* The issue doesn't happen at all for small payloads (resulting JSON up to a few KBs)
* It happens let's say for 1 out of 100 requests for medium payload (resulting JSON up to a few hundred KBs)
* It happens let's say for 1 out of 10 requests for big payloads (resulting JSON of several MBs)

So it's not a bug, but rather a performance issue, and it's not entirely the fault of jsonapi-serializer, because one could say the garbage collector of Ruby should handle this better.

EDIT: I tried to use **jemalloc** (article about jemalloc [here](https://medium.com/rubyinside/how-we-halved-our-memory-consumption-in-rails-with-jemalloc-86afa4e54aa3)), it was better, but still far from being okay (let's say instead of 5 seconds the request would take 4,5 seconds).

This behavior disappears when not using jsonapi-serializer.

EDIT 2: **The random request which is slowed down can be any endpoint, not only the endpoint(s) generating the big payloads.** For example, I have a `/dummy` endpoint which renders the static JSON response `{"hello": "world"}`, and this endpoint can take several seconds to complete when the issue occurs (it normal conditions, it only takes a few ms).

## Steps to Reproduce the Problem

1. Create a Rails project
2. Create models with relationships
3. Implement serializers for these models
4. Implement one or more endpoint(s) to use these serializers
5. Populate the DB with data
6. Call the endpoint(s) hundreds of times and time the response times. There should be spikes in response times regularly (it means a GC was triggered).

## Specifications

  - Version: 2.0.0
  - Ruby version: 2.7.0
  - Rails version: 6.0.3

**Comment by stas** [comment] 2020-08-05 16:10
@GuiTeK do you think we could reproduce this without using Rails? Rails by itself is already _a lot of haystack to find a needle_...

**Comment by ziggythehamster** [comment] 2020-08-11 22:56
When you're not using jsonapi-serializer, what are you using instead? What makes these payloads large? Large collections, or just lots of data in individual fields?

**Comment by GuiTeK** [comment] 2020-08-13 13:09
@stas Yes, I can try that next week. I could also enable instrumentation as you suggested in your PR #110.

@ziggythehamster We're only using jsonapi-serializer right now. Before, we were using the builtin Rails JSON serialization and didn't experience this weird issue.

**Also, I didn't explain this in my original post, but the random request which is slowed down can be any endpoint, not only the endpoint(s) generating the big payloads.** For example, I have a `/dummy` endpoint which renders the static JSON response `{"hello": "world"}`, and this endpoint can take several seconds to complete when the issue occurs (it normal conditions, it only takes a few ms).

For the question related to the payload size:
* There are about 3000 entries
* Each of these entries have:
    * 11 individual fields with small values (less than 50 bytes for each field)
    * 1 `has_one` relationship
    * 6 `belongs_to` relationships
    * 1 `has_many` relationship

**But for my tests, I don't `include` the relationships, so the resulting payload is in fact only 1,1 MB**.

**Comment by stas** [comment] 2020-08-16 13:46
> @ziggythehamster We're only using jsonapi-serializer right now. Before, we were using the builtin Rails JSON serialization and didn't experience this weird issue.

@GuiTeK what do you mean by _builtin Rails JSON serialization_? Rails doesn't have any support for JSON:API serialization!!!

Are we talking here about the JSON serialization or JSON:API serialization. I would like to kindly remind that these two a completely separate topics. You can learn more about JSON:API at https://jsonapi.org/

**Comment by stas** [comment] 2020-08-16 13:49
> **Also, I didn't explain this in my original post, but the random request which is slowed down can be any endpoint, not only the endpoint(s) generating the big payloads.** For example, I have a `/dummy` endpoint which renders the static JSON response `{"hello": "world"}`, and this endpoint can take several seconds to complete when the issue occurs (it normal conditions, it only takes a few ms).

This sounds like it's an issue caused by your setup. Again, `jsonapi/serializer` is a library. With the latest version, we're no longer doing any serialization at all. See this doc to enable alternative JSON serialization support (gems like `oj`):
https://github.com/jsonapi-serializer/jsonapi-serializer/blob/master/docs/json_serialization.md

**Comment by GuiTeK** [comment] 2020-08-19 15:03
> > @ziggythehamster We're only using jsonapi-serializer right now. Before, we were using the builtin Rails JSON serialization and didn't experience this weird issue.
> 
> @GuiTeK what do you mean by _builtin Rails JSON serialization_? Rails doesn't have any support for JSON:API serialization!!!
> 
> Are we talking here about the JSON serialization or JSON:API serialization. I would like to kindly remind that these two a completely separate topics. You can learn more about JSON:API at https://jsonapi.org/

Before, we were _not_ using JSON:API specification/format, we were using our own "format" and basically doing `my_object.to_json`.

**Comment by GuiTeK** [comment] 2020-08-19 15:26
I dug into jsonapi-serialiazer code and added some instrumentation code like in your PR #110.

Here is what the call stack looks like when using a serializer with a collection of ~3300 objects:
- `render` - 6.9 seconds
    - `to_json` - 6.9 seconds, of which about 0.2 second is spent in the actual JSON serialization (i.e. by [Oj](https://github.com/ohler55/oj)) once the Ruby objects have been generated
        - `serializable_hash` - 6.7 seconds
            - `hash_for_collection` - 6.7 seconds
            - `record_hash` - ~0.002 s/record
                - `id_from_record` - ~0.00002 s/record
                - `attributes_hash` - ~0.002 s/record
                - `relationships_hash` - ~0.00005 s/record

So clearly what takes all the time in my use case is `attributes_hash`. Do you see any obvious reason why @stas or is it expected that this method takes about this time to execute?

-----

Also, due to how the library works (all the objects are generated, then all the objects are serialized to JSON), **response streaming is not possible** and at some point all the objects involved in the response must be in memory at the same time. This can cause two problems:
* All the objects may not fit into memory (big data sets and/or small amounts of RAM such as in containers, VM, etc.)
* It can trigger GC problems/slowdowns (once again, we can also blame Ruby GC for this)

I understand changing this to make response streaming possible probably requires a lot of work and I'm not asking to change it, I'm just pointing out this issue.

**Comment by stas** [comment] 2020-08-30 15:03
> So clearly what ~takes~ was taking all the time is `attributes_hash`, and more specifically the `serialize` function of each attribute. **I finally found out that it was a missing `JOIN` (`includes(...)` in Rails/ActiveRecord) that was causing the big performance hit**.
> 
> Now, my 3300 objects collection renders in about 2.5 seconds, so that's about 0.0008 second/record.

@GuiTeK glad you found the cause of the slowness!



> Also, due to how the library works (all the objects are generated, then all the objects are serialized to JSON), **response streaming is not possible** and at some point all the objects involved in the response must be in memory at the same time. This can cause two problems:
> 
>     * All the objects may not fit into memory (big data sets and/or small amounts of RAM such as in containers, VM, etc.)
> 
>     * It can trigger GC problems/slowdowns (once again, we can also blame Ruby GC for this)
> 
> 
> I understand changing this to make response streaming possible probably requires a lot of work and I'm not asking to change it, I'm just pointing out this issue.

As far as I know, JSON streaming is not supported by it's spec, there's an extension or some project related to it, but nothing that we could just "tweak" to get such a feature easily.

I generally recommend paginating large responses. JSONAPI supports and documents it and aside from the issues you're describing, your UI will end up much snappier having to deal/render tons of data.

If I may... [consider `jsonapi.rb` for pagination.](https://github.com/stas/jsonapi.rb#pagination)

In the meantime, I'll be closing this. Thank you!

**Closed by stas** 2020-08-30 15:03 UTC
Labels: question

**Comment by tonydehnke** [comment] 2020-08-31 05:07
@GuiTeK - I think I might be a experiencing something similar,  can you explain where or how you fixed things a bit more?   Also is this something that should get submitted to Rails as a fix?

Thanks!
