### ISSUE TITLE
Why do relationship ids get included by default

### ISSUE THREAD

**Issue by kapso** [jsonapi-serializer/jsonapi-serializer#172] opened 2021-02-22 14:31 UTC
Relationship `id`'s get included in the json response even though the `has_many` relationship is not manifested in `include:` list, why?

**Comment by stas** [comment] 2021-02-22 20:30
@kapso please take a look at the spec:
https://jsonapi.org/format/#document-resource-object-relationships

>  A “relationship object” MUST contain at least one of the following:

I'll be closing this for now. Thanks! :hugs:

**Closed by stas** 2021-02-22 20:30 UTC

**Comment by kapso** [comment] 2021-02-25 06:39
@stas but that rule is broken if I have something like this, right?

`has_many :products, if: ->(_record, params) { params[:order_products] }`

So I am guessing the default behavior is to follow the rule, unless the developer wants to break it?

**Comment by stas** [comment] 2021-02-25 10:56
@kapso would you be kind to share an example or a test-case to reproduce this. I'm not sure what's the logic behind your implementation :flushed:

**Comment by kapso** [comment] 2021-02-25 19:50
@stas So here's an example of a serializer...

```ruby
class OrderSerializer
  attributes :id, :order_number, :created_at

  has_many :products
end
```

When I do `render json: OrderSerializer.new(@order)`, relationship product `id`'s get included even though I did not use `include: [:products]`

**Comment by stas** [comment] 2021-02-26 10:59
> When I do `render json: OrderSerializer.new(@order)`, relationship product `id`'s get included even though I did not use `include: [:products]`

This is part of the specification which I linked for you earlier. The JSONAPI relationship **SHOULD ALWAYS** include either `data`, `links` or `meta`. This is independent from `include`. Please give it a quick read, I think it will make sense :relaxed:

**Comment by MarcelEeken** [comment] 2021-07-20 14:06
Hey @stas , I'm also interested in this issue, because I don't always want the relationship to include all the ids when I'm not also including them.

Since the spec specifies that either `data`, `links` or `meta` needs to be present. Is it possible or okay to allow for an option to specify that instead of adding a list of ids, a link is added with the route to fetch the related resources. For that we can follow this part of the spec https://jsonapi.org/format/#document-resource-object-related-resource-links. (I think this is also done by default in the [JSONAPI::Resources](https://github.com/cerebris/jsonapi-resources) gem)

**Comment by stas** [comment] 2021-07-20 15:04
> Since the spec specifies that either `data`, `links` or `meta` needs to be present. Is it possible or okay to allow for an option to specify that instead of adding a list of ids, a link is added with the route to fetch the related resources.

Hey @MarcelEeken I opened a new issue related to your question, let's move the conversation into #197
