### ISSUE TITLE
`lazy_load_data` overwrites `include` and does not render relationship data

### ISSUE THREAD

**Issue by mocerinoj** [jsonapi-serializer/jsonapi-serializer#23] opened 2019-11-22 17:42 UTC
When lazy loading polymorphic relationships.. when including the relationship, the relationship object comes through but the relationship data does not.

```ruby
# provider_lead_serializer.rb
class ProviderLeadSerializer
  include FastJsonapi::ObjectSerializer

  belongs_to :owner, polymorphic: true, lazy_load_data: true

  ...
end

# agent_serializer.rb
class AgentSerializer
  include FastJsonapi::ObjectSerializer
  ...
end
```

Without including the relationship, the data is not loaded (as expected):
```ruby
ProviderLeadSerializer.new(provider_lead)
```
yields:
```json
{
  "data": [
    {
      "id": 123,
      "type": "provider_lead",
      "attributes": {},
      "relationships": {
        "owner": { }
      }
    }
  ],
  "included": []
}
```

Then, I want to explicitly include the `owner` relationship:
```ruby
ProviderLeadSerializer.new(provider_lead, { include: [:owner] })
```
yields:
```json
{
  "data": [
    {
      "id": 123,
      "type": "provider_lead",
      "attributes": {},
      "relationships": {
        "owner": { }
      }
    }
  ],
  "included": [
    {
      "id": 456,
      "type": "agent",
      "attributes": {}
    }
  ]
}
```
^^^ This is missing the data on `provider_lead.relationships`. If i remove `lazy_load_data: true`, everything works as expect.

Expected JSON would be:
```json
{
  "data": [
    {
      "id": 123,
      "type": "provider_lead",
      "attributes": {},
      "relationships": {
        "owner": {
          "data": {
            "id": 456,
            "type": "agent"
          }
        }
      }
    }
  ],
  "included": [
    {
      "id": 456,
      "type": "agent",
      "attributes": {}
    }
  ]
}
```

**Comment by stas** [comment] 2019-11-23 12:17
@mocerinoj it looks like this parameter (`lazy_load_data: true`) was designed to work this way:
https://github.com/fast-jsonapi/fast_jsonapi/blob/fdcaed6f0d72cf793b3117a5081de5fbd7466574/spec/lib/object_serializer_relationship_links_spec.rb#L53-L68

So I'm not sure what's broken here, could you help us understand your concern please? :)

**Comment by mocerinoj** [comment] 2019-11-23 16:45
That is true and expected (see my first example). However, when explicitly including that lazy loaded relationship, it should render the key.  https://github.com/fast-jsonapi/fast_jsonapi/blob/master/lib/fast_jsonapi/relationship.rb#L42

**Comment by christophersansone** [comment] 2019-12-17 18:12
@mocerinoj What are you expecting `lazy_load_data` to do in this situation?  If removing `lazy_load_data` gives you the proper output, then doesn't that solve it for you?  Maybe you are expecting `lazy_load_data` to change how the relationship data is fetched from the object?  That is not what it does.

@stas is correct that `lazy_load_data` was implemented with the expectation that it worked in conjunction with `links`.  Here is the [commit](https://github.com/fast-jsonapi/fast_jsonapi/commit/85b41c45d4c1f1328908811d353054cada306f2b) and [PR](https://github.com/Netflix/fast_jsonapi/pull/294).

That said, I don't think anyone has decided how `lazy_load_data` should behave when `links` is not specified.  I think the assumption is that it would not behave any differently.  If it behaves differently when other options are specified, I would consider that a bug that should be fixed.  I would also consider adding some validation to ensure that a relationship does not specify `lazy_load_data` without `links`, but that is probably a larger topic as we continue to refine the API.  I do agree that it is unclear though.

**Comment by stas** [comment] 2020-01-05 18:22
Hmm, I'm taking another look at this `lazy_load_data` and it seems an incredibly unhelpful name for what it does in fact haha

May I suggest we fix this and also include a more relevant name to reflect the documentation:
https://jsonapi.org/format/#document-resource-object-relationships

Like `resource_linkage: false`, this way we don't need to invent how to explain it?!

It seems like we should cover the following use-cases:
 * [x] Resource linkage occurs by default
 * [x] Resource linkage occurs when relevant `included` parameter value is present
 * [x] Resource linkage skipped when relevant parameter is passed
 * [ ] Resource linkage occurs when relevant parameter is passed and relevant `included` parameter value is present

**Comment by cilim** [comment] 2020-02-18 09:24
fast_jsonapi includes the ID's of the relationships automatically, even though the client didn't ask it to...in my situation this really isn't what I want. What I would like to be able is to get a response like this when the client doesn't send the `include` query` params:

```
{
  "data": [
    {
      "id": 123,
      "type": "provider_lead",
      "attributes": {},
      "relationships": {
        "owner": {
           "meta":{
              included: false
            }
        }
      }
    }
  ]
}
```

or like this when he sends `?include=owner`:

```
{
  "data": [
    {
      "id": 123,
      "type": "provider_lead",
      "attributes": {},
      "relationships": {
        "owner": {
          "data": {
            "id": 456,
            "type": "agent"
          }
        }
      }
    }
  ],
  "included": [
    {
      "id": 456,
      "type": "agent",
      "attributes": {}
    }
  ]
}
```
I thought that this is done with setting `lazy_load_data` to true, but I see from here that it's just a really bad name.

However, I'm curious whether or not my requirement is planned to implement or not? https://github.com/jsonapi-rb/jsonapi-rails has it implemented like this btw...

**Comment by christophersansone** [comment] 2020-02-18 13:45
@cilim I'd recommend checking out the discussion in  #21, as it may be more closely related.

@stas I like the idea of using the terminology in the spec... but I think this one might be kind of confusing, as `links` and `resource_linkage` seem too similar.  I think someone would have to read the spec to know what `resource_linkage` means.  People will better understand it if it were more closely named to the question they are asking themselves: _should I include `data` or not?_

How about simply `include_data`?  IIRC, ActiveModel Serializers uses this term.  FWIW, I reviewed [the original PR](https://github.com/Netflix/fast_jsonapi/pull/294), and it looks like I originally recommended the option to be called `include_data`, but I was outvoted.  I still think it's a viable option.

Another idea that would align it more closely to the spec is to have a `data` option.  If `false`, it would not include `data` in the output.  If `true`, it would include the `data` in the output.  If a `Proc`, it can define how to fetch the data (equivalent to how `object_block` works today), or whether the data should be output at all.  Some examples:

```ruby
# data is true by default, so these are equivalent
has_many :actors
has_many :actors, data: true

# when specifying links and no data
has_many :actors, data: false, links: { ... }

# describes HOW to fetch the data, by returning an object, array, or nil
has_many :actors, data: -> { |object, params| object.stars }

# describes IF the data should be specified, by returning a boolean
has_many :actors, data: -> { |object, params| !!params[:include_actors] }
```

This seems like a really succinct and intuitive approach.  The fact that the `data` JSON output can never be boolean allows us to use the same key to define both the "if behavior" and the "how behavior".

**Comment by stas** [comment] 2020-02-25 17:06
> How about simply `include_data`? IIRC, ActiveModel Serializers uses this term. FWIW, I reviewed [the original PR](https://github.com/Netflix/fast_jsonapi/pull/294), and it looks like I originally recommended the option to be called `include_data`, but I was outvoted. I still think it's a viable option.

I think that will work. As long as things are clear...


> Another idea that would align it more closely to the spec is to have a `data` option. If `false`, it would not include `data` in the output. If `true`, it would include the `data` in the output. If a `Proc`, it can define how to fetch the data (equivalent to how `object_block` works today), or whether the data should be output at all. Some examples:

Sounds like it would interfere with the support covered by the `if: -> {}`, which in fact appeals to me more, and could be a way to deprecate this option and let the users leverage the more versatile `if: ` API. Though it will indeed require a bit more legwork...

So everyone will probably not like it :sweat_smile:

**Closed** 2023-07-31 20:24 UTC
